/* Author: Flame 'Em -_-rormommemm-_-#8020 */
function customtheme () {
    injecttheme("CTH", ".scrollableContainer-15eg7h {overflow-x: hidden; overflow-y: scroll; background-color: #2a3038; max-height: 50vh; border-radius: 8px;}")
    injecttheme("CTH", ".wordmarkWindows-2dq6rw::after {content: 'PrimaryX'; display: block; font-size: 9pt; font-weight: 800;}")
    injecttheme("CTH", ".wordmarkWindows-2dq6rw > svg { display: none; }")
    injecttheme("CTH", ".bg-1QIAus .bg-1QIAus { background-color: transparent; background-position: var(--backgroundPosition); background-repeat: var(--backgroundRepeat); background-size: var(--backgroundSize); background-image: var(--backgroundImage); opacity: var(--backgroundOpacity); filter: blur(var(--backgroundBlur)) }")
    injecttheme("CTH", ".homeIcon-r0w4ny path { fill: transparent }")
    injecttheme("CTH", ".homeIcon-r0w4ny { background: url(https://i.postimg.cc/2y6GBcsv/PrimaryX.png) center/cover no-repeat; min-width: 48px; min-height: 48px; }")
    injecttheme("CTH", "* { --background-primary: 30,30,30; --background-secondary: 20,20,20; --background-secondary-alt: 15,15,15; --background-accent: 50,50,50; --background-floating: #050506; --scrollbar-thin-track: #2e2e2e; --channeltextarea-background: #A96762}")
    injecttheme("CTH", ".attachButtonPlus-3IYelE { color: dodgerblue }")
    injecttheme("CTH", ".icon-Lupfh- { color: blue }")
    injecttheme("CTH", ".app-2CXKsg button { color: #9e9e9e }")
    injecttheme("CTH", ".userPopout-2j1gM4,")
    injecttheme("CTH", ".bodyInnerWrapper-2bQs1k { background-color: #191C24; }")
    injecttheme("CTH", ".avatar-2Vndt_ { border: 6px solid #191C24; background-color: #191C24; }")
    injecttheme("CTH", ".footer-3naVBw { background-color: #191C24; }")
    injecttheme("CTH", ".body-1Ukv50 { background-color: #191C24; }")
    injecttheme("CTH", ".tabBarContainer-sCZC4w { background-color: #191C24; }")
    injecttheme("CTH", ".statusItem-2hiCNB { transition: transform 250ms; }")
    injecttheme("CTH", ".statusItem-2hiCNB:hover { transform: translateX(10px); }")
    injecttheme("CTH", ".icon-Lupfh- { background-color: #2e2e2e; }")
    injecttheme("CTH", ".typeWindows-2-g3UY withFrame-2dL45i titleBar-1it3bQ horizontalReverse-2QssvL flex-3BkGQD directionRowReverse-HZatnx justifyStart-2Mwniq alignStretch-Uwowzr { border-bottom: #8c38ff; }")
    injecttheme("CTH", ":root { --server-listing-width: 72px; --font-size: 100%; }")
    injecttheme("CTH", ".input-2z42oC,")
    injecttheme("CTH", ".scrollableContainer-15eg7h { background-color: #292929; transition: background-color 0.2s ease, border-color 0.2s ease; border: 1px solid transparent; outline: none; }")
    injecttheme("CTH", ".input-2z42oC:hover,")
    injecttheme("CTH", ".scrollableContainer-15eg7h:hover { border-color: #0090E7; background-color: #2e2c2c; }")
    injecttheme("CTH", ".input-cIJ7To:focus-within,")
    injecttheme("CTH", ".scrollableContainer-15eg7h:focus-within { background-color: #2e2c2c; border-color: var(--color-brand-lighter); }")
    injecttheme("CTH", ".scrollableContainer-15eg7h { border: 1px solid transparent; border-radius: 3px; }")
    injecttheme("CTH", ".jumpToPresentBar-1cEnH0 { border: 1px solid transparent; border-radius: 5px; width: 370px; margin-left: 1px; margin-bottom: -3px!important; }")
    injecttheme("CTH", ".topic-TCb_qw > .wrapper-3WhCwL > .channelIcon-1MN1lz,")
    injecttheme("CTH", ".embedFooterText-28V_Wb > .wrapper-3WhCwL > .channelIcon-1MN1lz { width: calc(1.05rem * 1.05 / 1.3); height: 1.05rem; }")
    injecttheme("CTH", ".avatar-1EWyVD.wrapper-1VLyxH:active { animation: slide-bck-center 0.45s cubic-bezier(0.470, 0.000, 0.745, 0.715) both; }")//this animation is not working rn im fixing it
    injecttheme("CTH", ".lowerBadge-3WTshO { animation: bounce-top 0.9s both; }")
}
